[project]
name = "kanban-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dynaconf>=3.2.11",
]

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
    "ipython>=8.18.1",
    "pytest>=8.4.2",
    "ty>=0.0.1a21",
]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

[tool.ruff]
line-length = 79
target-version = "py39"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
